/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebRouteImport } from './routes/web'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as ReservarOkRouteImport } from './routes/reservar-ok'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebIndexRouteImport } from './routes/web.index'
import { Route as StaysIndexRouteImport } from './routes/stays.index'
import { Route as WebEventsRouteImport } from './routes/web.events'
import { Route as WebCommunitiesRouteImport } from './routes/web.communities'
import { Route as StaysTripsRouteImport } from './routes/stays.trips'
import { Route as StaysSpacesRouteImport } from './routes/stays.spaces'
import { Route as StaysLoyaltyRouteImport } from './routes/stays.loyalty'
import { Route as StaysInvoicesRouteImport } from './routes/stays.invoices'
import { Route as StaysIncidentsRouteImport } from './routes/stays.incidents'
import { Route as StaysCommunityRouteImport } from './routes/stays.community'
import { Route as StaysAccountRouteImport } from './routes/stays.account'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppReservationsRouteImport } from './routes/_app.reservations'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRatesRouteImport } from './routes/_app.rates'
import { Route as AppPromosRouteImport } from './routes/_app.promos'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppExtrasRouteImport } from './routes/_app.extras'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as WebUploadBookingIdRouteImport } from './routes/web.upload.$bookingId'
import { Route as WebSignBookingIdRouteImport } from './routes/web.sign.$bookingId'
import { Route as WebRoomRoomIdRouteImport } from './routes/web.room.$roomId'
import { Route as WebEventEventIdRouteImport } from './routes/web.event.$eventId'
import { Route as WebCommunityCommunityIdRouteImport } from './routes/web.community.$communityId'
import { Route as WebCheckoutBookingIdRouteImport } from './routes/web.checkout.$bookingId'
import { Route as WebBookingBookingIdRouteImport } from './routes/web.booking.$bookingId'
import { Route as WebBookRoomIdRouteImport } from './routes/web.book.$roomId'
import { Route as StaysSignBookingIdRouteImport } from './routes/stays.sign.$bookingId'
import { Route as StaysPropertyPropertyIdRouteImport } from './routes/stays.property.$propertyId'
import { Route as StaysEventEventIdRouteImport } from './routes/stays.event.$eventId'
import { Route as StaysCheckoutBookingIdRouteImport } from './routes/stays.checkout.$bookingId'
import { Route as StaysBookingBookingIdRouteImport } from './routes/stays.booking.$bookingId'
import { Route as StaysBookRoomIdRouteImport } from './routes/stays.book.$roomId'
import { Route as AppAdminManualRouteImport } from './routes/_app.admin.manual'

const WebRoute = WebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarOkRoute = ReservarOkRouteImport.update({
  id: '/reservar-ok',
  path: '/reservar-ok',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebRoute,
} as any)
const StaysIndexRoute = StaysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaysRoute,
} as any)
const WebEventsRoute = WebEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => WebRoute,
} as any)
const WebCommunitiesRoute = WebCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => WebRoute,
} as any)
const StaysTripsRoute = StaysTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => StaysRoute,
} as any)
const StaysSpacesRoute = StaysSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => StaysRoute,
} as any)
const StaysLoyaltyRoute = StaysLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => StaysRoute,
} as any)
const StaysInvoicesRoute = StaysInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => StaysRoute,
} as any)
const StaysIncidentsRoute = StaysIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => StaysRoute,
} as any)
const StaysCommunityRoute = StaysCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => StaysRoute,
} as any)
const StaysAccountRoute = StaysAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StaysRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRatesRoute = AppRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AppRoute,
} as any)
const AppPromosRoute = AppPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppExtrasRoute = AppExtrasRouteImport.update({
  id: '/extras',
  path: '/extras',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const WebUploadBookingIdRoute = WebUploadBookingIdRouteImport.update({
  id: '/upload/$bookingId',
  path: '/upload/$bookingId',
  getParentRoute: () => WebRoute,
} as any)
const WebSignBookingIdRoute = WebSignBookingIdRouteImport.update({
  id: '/sign/$bookingId',
  path: '/sign/$bookingId',
  getParentRoute: () => WebRoute,
} as any)
const WebRoomRoomIdRoute = WebRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => WebRoute,
} as any)
const WebEventEventIdRoute = WebEventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => WebRoute,
} as any)
const WebCommunityCommunityIdRoute = WebCommunityCommunityIdRouteImport.update({
  id: '/community/$communityId',
  path: '/community/$communityId',
  getParentRoute: () => WebRoute,
} as any)
const WebCheckoutBookingIdRoute = WebCheckoutBookingIdRouteImport.update({
  id: '/checkout/$bookingId',
  path: '/checkout/$bookingId',
  getParentRoute: () => WebRoute,
} as any)
const WebBookingBookingIdRoute = WebBookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => WebRoute,
} as any)
const WebBookRoomIdRoute = WebBookRoomIdRouteImport.update({
  id: '/book/$roomId',
  path: '/book/$roomId',
  getParentRoute: () => WebRoute,
} as any)
const StaysSignBookingIdRoute = StaysSignBookingIdRouteImport.update({
  id: '/sign/$bookingId',
  path: '/sign/$bookingId',
  getParentRoute: () => StaysRoute,
} as any)
const StaysPropertyPropertyIdRoute = StaysPropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => StaysRoute,
} as any)
const StaysEventEventIdRoute = StaysEventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => StaysRoute,
} as any)
const StaysCheckoutBookingIdRoute = StaysCheckoutBookingIdRouteImport.update({
  id: '/checkout/$bookingId',
  path: '/checkout/$bookingId',
  getParentRoute: () => StaysRoute,
} as any)
const StaysBookingBookingIdRoute = StaysBookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => StaysRoute,
} as any)
const StaysBookRoomIdRoute = StaysBookRoomIdRouteImport.update({
  id: '/book/$roomId',
  path: '/book/$roomId',
  getParentRoute: () => StaysRoute,
} as any)
const AppAdminManualRoute = AppAdminManualRouteImport.update({
  id: '/admin/manual',
  path: '/admin/manual',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/reservar-ok': typeof ReservarOkRoute
  '/stays': typeof StaysRouteWithChildren
  '/web': typeof WebRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/customers': typeof AppCustomersRoute
  '/extras': typeof AppExtrasRoute
  '/journal': typeof AppJournalRoute
  '/promos': typeof AppPromosRoute
  '/rates': typeof AppRatesRoute
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRoute
  '/rooms': typeof AppRoomsRoute
  '/today': typeof AppTodayRoute
  '/stays/account': typeof StaysAccountRoute
  '/stays/community': typeof StaysCommunityRoute
  '/stays/incidents': typeof StaysIncidentsRoute
  '/stays/invoices': typeof StaysInvoicesRoute
  '/stays/loyalty': typeof StaysLoyaltyRoute
  '/stays/spaces': typeof StaysSpacesRoute
  '/stays/trips': typeof StaysTripsRoute
  '/web/communities': typeof WebCommunitiesRoute
  '/web/events': typeof WebEventsRoute
  '/stays/': typeof StaysIndexRoute
  '/web/': typeof WebIndexRoute
  '/admin/manual': typeof AppAdminManualRoute
  '/stays/book/$roomId': typeof StaysBookRoomIdRoute
  '/stays/booking/$bookingId': typeof StaysBookingBookingIdRoute
  '/stays/checkout/$bookingId': typeof StaysCheckoutBookingIdRoute
  '/stays/event/$eventId': typeof StaysEventEventIdRoute
  '/stays/property/$propertyId': typeof StaysPropertyPropertyIdRoute
  '/stays/sign/$bookingId': typeof StaysSignBookingIdRoute
  '/web/book/$roomId': typeof WebBookRoomIdRoute
  '/web/booking/$bookingId': typeof WebBookingBookingIdRoute
  '/web/checkout/$bookingId': typeof WebCheckoutBookingIdRoute
  '/web/community/$communityId': typeof WebCommunityCommunityIdRoute
  '/web/event/$eventId': typeof WebEventEventIdRoute
  '/web/room/$roomId': typeof WebRoomRoomIdRoute
  '/web/sign/$bookingId': typeof WebSignBookingIdRoute
  '/web/upload/$bookingId': typeof WebUploadBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/reservar-ok': typeof ReservarOkRoute
  '/calendar': typeof AppCalendarRoute
  '/customers': typeof AppCustomersRoute
  '/extras': typeof AppExtrasRoute
  '/journal': typeof AppJournalRoute
  '/promos': typeof AppPromosRoute
  '/rates': typeof AppRatesRoute
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRoute
  '/rooms': typeof AppRoomsRoute
  '/today': typeof AppTodayRoute
  '/stays/account': typeof StaysAccountRoute
  '/stays/community': typeof StaysCommunityRoute
  '/stays/incidents': typeof StaysIncidentsRoute
  '/stays/invoices': typeof StaysInvoicesRoute
  '/stays/loyalty': typeof StaysLoyaltyRoute
  '/stays/spaces': typeof StaysSpacesRoute
  '/stays/trips': typeof StaysTripsRoute
  '/web/communities': typeof WebCommunitiesRoute
  '/web/events': typeof WebEventsRoute
  '/stays': typeof StaysIndexRoute
  '/web': typeof WebIndexRoute
  '/admin/manual': typeof AppAdminManualRoute
  '/stays/book/$roomId': typeof StaysBookRoomIdRoute
  '/stays/booking/$bookingId': typeof StaysBookingBookingIdRoute
  '/stays/checkout/$bookingId': typeof StaysCheckoutBookingIdRoute
  '/stays/event/$eventId': typeof StaysEventEventIdRoute
  '/stays/property/$propertyId': typeof StaysPropertyPropertyIdRoute
  '/stays/sign/$bookingId': typeof StaysSignBookingIdRoute
  '/web/book/$roomId': typeof WebBookRoomIdRoute
  '/web/booking/$bookingId': typeof WebBookingBookingIdRoute
  '/web/checkout/$bookingId': typeof WebCheckoutBookingIdRoute
  '/web/community/$communityId': typeof WebCommunityCommunityIdRoute
  '/web/event/$eventId': typeof WebEventEventIdRoute
  '/web/room/$roomId': typeof WebRoomRoomIdRoute
  '/web/sign/$bookingId': typeof WebSignBookingIdRoute
  '/web/upload/$bookingId': typeof WebUploadBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/reservar-ok': typeof ReservarOkRoute
  '/stays': typeof StaysRouteWithChildren
  '/web': typeof WebRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/extras': typeof AppExtrasRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/promos': typeof AppPromosRoute
  '/_app/rates': typeof AppRatesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/reservations': typeof AppReservationsRoute
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/today': typeof AppTodayRoute
  '/stays/account': typeof StaysAccountRoute
  '/stays/community': typeof StaysCommunityRoute
  '/stays/incidents': typeof StaysIncidentsRoute
  '/stays/invoices': typeof StaysInvoicesRoute
  '/stays/loyalty': typeof StaysLoyaltyRoute
  '/stays/spaces': typeof StaysSpacesRoute
  '/stays/trips': typeof StaysTripsRoute
  '/web/communities': typeof WebCommunitiesRoute
  '/web/events': typeof WebEventsRoute
  '/stays/': typeof StaysIndexRoute
  '/web/': typeof WebIndexRoute
  '/_app/admin/manual': typeof AppAdminManualRoute
  '/stays/book/$roomId': typeof StaysBookRoomIdRoute
  '/stays/booking/$bookingId': typeof StaysBookingBookingIdRoute
  '/stays/checkout/$bookingId': typeof StaysCheckoutBookingIdRoute
  '/stays/event/$eventId': typeof StaysEventEventIdRoute
  '/stays/property/$propertyId': typeof StaysPropertyPropertyIdRoute
  '/stays/sign/$bookingId': typeof StaysSignBookingIdRoute
  '/web/book/$roomId': typeof WebBookRoomIdRoute
  '/web/booking/$bookingId': typeof WebBookingBookingIdRoute
  '/web/checkout/$bookingId': typeof WebCheckoutBookingIdRoute
  '/web/community/$communityId': typeof WebCommunityCommunityIdRoute
  '/web/event/$eventId': typeof WebEventEventIdRoute
  '/web/room/$roomId': typeof WebRoomRoomIdRoute
  '/web/sign/$bookingId': typeof WebSignBookingIdRoute
  '/web/upload/$bookingId': typeof WebUploadBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reservar'
    | '/reservar-ok'
    | '/stays'
    | '/web'
    | '/calendar'
    | '/customers'
    | '/extras'
    | '/journal'
    | '/promos'
    | '/rates'
    | '/reports'
    | '/reservations'
    | '/rooms'
    | '/today'
    | '/stays/account'
    | '/stays/community'
    | '/stays/incidents'
    | '/stays/invoices'
    | '/stays/loyalty'
    | '/stays/spaces'
    | '/stays/trips'
    | '/web/communities'
    | '/web/events'
    | '/stays/'
    | '/web/'
    | '/admin/manual'
    | '/stays/book/$roomId'
    | '/stays/booking/$bookingId'
    | '/stays/checkout/$bookingId'
    | '/stays/event/$eventId'
    | '/stays/property/$propertyId'
    | '/stays/sign/$bookingId'
    | '/web/book/$roomId'
    | '/web/booking/$bookingId'
    | '/web/checkout/$bookingId'
    | '/web/community/$communityId'
    | '/web/event/$eventId'
    | '/web/room/$roomId'
    | '/web/sign/$bookingId'
    | '/web/upload/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reservar'
    | '/reservar-ok'
    | '/calendar'
    | '/customers'
    | '/extras'
    | '/journal'
    | '/promos'
    | '/rates'
    | '/reports'
    | '/reservations'
    | '/rooms'
    | '/today'
    | '/stays/account'
    | '/stays/community'
    | '/stays/incidents'
    | '/stays/invoices'
    | '/stays/loyalty'
    | '/stays/spaces'
    | '/stays/trips'
    | '/web/communities'
    | '/web/events'
    | '/stays'
    | '/web'
    | '/admin/manual'
    | '/stays/book/$roomId'
    | '/stays/booking/$bookingId'
    | '/stays/checkout/$bookingId'
    | '/stays/event/$eventId'
    | '/stays/property/$propertyId'
    | '/stays/sign/$bookingId'
    | '/web/book/$roomId'
    | '/web/booking/$bookingId'
    | '/web/checkout/$bookingId'
    | '/web/community/$communityId'
    | '/web/event/$eventId'
    | '/web/room/$roomId'
    | '/web/sign/$bookingId'
    | '/web/upload/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reservar'
    | '/reservar-ok'
    | '/stays'
    | '/web'
    | '/_app/calendar'
    | '/_app/customers'
    | '/_app/extras'
    | '/_app/journal'
    | '/_app/promos'
    | '/_app/rates'
    | '/_app/reports'
    | '/_app/reservations'
    | '/_app/rooms'
    | '/_app/today'
    | '/stays/account'
    | '/stays/community'
    | '/stays/incidents'
    | '/stays/invoices'
    | '/stays/loyalty'
    | '/stays/spaces'
    | '/stays/trips'
    | '/web/communities'
    | '/web/events'
    | '/stays/'
    | '/web/'
    | '/_app/admin/manual'
    | '/stays/book/$roomId'
    | '/stays/booking/$bookingId'
    | '/stays/checkout/$bookingId'
    | '/stays/event/$eventId'
    | '/stays/property/$propertyId'
    | '/stays/sign/$bookingId'
    | '/web/book/$roomId'
    | '/web/booking/$bookingId'
    | '/web/checkout/$bookingId'
    | '/web/community/$communityId'
    | '/web/event/$eventId'
    | '/web/room/$roomId'
    | '/web/sign/$bookingId'
    | '/web/upload/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReservarRoute: typeof ReservarRoute
  ReservarOkRoute: typeof ReservarOkRoute
  StaysRoute: typeof StaysRouteWithChildren
  WebRoute: typeof WebRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web': {
      id: '/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar-ok': {
      id: '/reservar-ok'
      path: '/reservar-ok'
      fullPath: '/reservar-ok'
      preLoaderRoute: typeof ReservarOkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web/': {
      id: '/web/'
      path: '/'
      fullPath: '/web/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof WebRoute
    }
    '/stays/': {
      id: '/stays/'
      path: '/'
      fullPath: '/stays/'
      preLoaderRoute: typeof StaysIndexRouteImport
      parentRoute: typeof StaysRoute
    }
    '/web/events': {
      id: '/web/events'
      path: '/events'
      fullPath: '/web/events'
      preLoaderRoute: typeof WebEventsRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/communities': {
      id: '/web/communities'
      path: '/communities'
      fullPath: '/web/communities'
      preLoaderRoute: typeof WebCommunitiesRouteImport
      parentRoute: typeof WebRoute
    }
    '/stays/trips': {
      id: '/stays/trips'
      path: '/trips'
      fullPath: '/stays/trips'
      preLoaderRoute: typeof StaysTripsRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/spaces': {
      id: '/stays/spaces'
      path: '/spaces'
      fullPath: '/stays/spaces'
      preLoaderRoute: typeof StaysSpacesRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/loyalty': {
      id: '/stays/loyalty'
      path: '/loyalty'
      fullPath: '/stays/loyalty'
      preLoaderRoute: typeof StaysLoyaltyRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/invoices': {
      id: '/stays/invoices'
      path: '/invoices'
      fullPath: '/stays/invoices'
      preLoaderRoute: typeof StaysInvoicesRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/incidents': {
      id: '/stays/incidents'
      path: '/incidents'
      fullPath: '/stays/incidents'
      preLoaderRoute: typeof StaysIncidentsRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/community': {
      id: '/stays/community'
      path: '/community'
      fullPath: '/stays/community'
      preLoaderRoute: typeof StaysCommunityRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/account': {
      id: '/stays/account'
      path: '/account'
      fullPath: '/stays/account'
      preLoaderRoute: typeof StaysAccountRouteImport
      parentRoute: typeof StaysRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations': {
      id: '/_app/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rates': {
      id: '/_app/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof AppRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promos': {
      id: '/_app/promos'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof AppPromosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extras': {
      id: '/_app/extras'
      path: '/extras'
      fullPath: '/extras'
      preLoaderRoute: typeof AppExtrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/web/upload/$bookingId': {
      id: '/web/upload/$bookingId'
      path: '/upload/$bookingId'
      fullPath: '/web/upload/$bookingId'
      preLoaderRoute: typeof WebUploadBookingIdRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/sign/$bookingId': {
      id: '/web/sign/$bookingId'
      path: '/sign/$bookingId'
      fullPath: '/web/sign/$bookingId'
      preLoaderRoute: typeof WebSignBookingIdRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/room/$roomId': {
      id: '/web/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/web/room/$roomId'
      preLoaderRoute: typeof WebRoomRoomIdRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/event/$eventId': {
      id: '/web/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/web/event/$eventId'
      preLoaderRoute: typeof WebEventEventIdRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/community/$communityId': {
      id: '/web/community/$communityId'
      path: '/community/$communityId'
      fullPath: '/web/community/$communityId'
      preLoaderRoute: typeof WebCommunityCommunityIdRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/checkout/$bookingId': {
      id: '/web/checkout/$bookingId'
      path: '/checkout/$bookingId'
      fullPath: '/web/checkout/$bookingId'
      preLoaderRoute: typeof WebCheckoutBookingIdRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/booking/$bookingId': {
      id: '/web/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/web/booking/$bookingId'
      preLoaderRoute: typeof WebBookingBookingIdRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/book/$roomId': {
      id: '/web/book/$roomId'
      path: '/book/$roomId'
      fullPath: '/web/book/$roomId'
      preLoaderRoute: typeof WebBookRoomIdRouteImport
      parentRoute: typeof WebRoute
    }
    '/stays/sign/$bookingId': {
      id: '/stays/sign/$bookingId'
      path: '/sign/$bookingId'
      fullPath: '/stays/sign/$bookingId'
      preLoaderRoute: typeof StaysSignBookingIdRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/property/$propertyId': {
      id: '/stays/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/stays/property/$propertyId'
      preLoaderRoute: typeof StaysPropertyPropertyIdRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/event/$eventId': {
      id: '/stays/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/stays/event/$eventId'
      preLoaderRoute: typeof StaysEventEventIdRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/checkout/$bookingId': {
      id: '/stays/checkout/$bookingId'
      path: '/checkout/$bookingId'
      fullPath: '/stays/checkout/$bookingId'
      preLoaderRoute: typeof StaysCheckoutBookingIdRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/booking/$bookingId': {
      id: '/stays/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/stays/booking/$bookingId'
      preLoaderRoute: typeof StaysBookingBookingIdRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/book/$roomId': {
      id: '/stays/book/$roomId'
      path: '/book/$roomId'
      fullPath: '/stays/book/$roomId'
      preLoaderRoute: typeof StaysBookRoomIdRouteImport
      parentRoute: typeof StaysRoute
    }
    '/_app/admin/manual': {
      id: '/_app/admin/manual'
      path: '/admin/manual'
      fullPath: '/admin/manual'
      preLoaderRoute: typeof AppAdminManualRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppExtrasRoute: typeof AppExtrasRoute
  AppJournalRoute: typeof AppJournalRoute
  AppPromosRoute: typeof AppPromosRoute
  AppRatesRoute: typeof AppRatesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppAdminManualRoute: typeof AppAdminManualRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppExtrasRoute: AppExtrasRoute,
  AppJournalRoute: AppJournalRoute,
  AppPromosRoute: AppPromosRoute,
  AppRatesRoute: AppRatesRoute,
  AppReportsRoute: AppReportsRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppTodayRoute: AppTodayRoute,
  AppAdminManualRoute: AppAdminManualRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface StaysRouteChildren {
  StaysAccountRoute: typeof StaysAccountRoute
  StaysCommunityRoute: typeof StaysCommunityRoute
  StaysIncidentsRoute: typeof StaysIncidentsRoute
  StaysInvoicesRoute: typeof StaysInvoicesRoute
  StaysLoyaltyRoute: typeof StaysLoyaltyRoute
  StaysSpacesRoute: typeof StaysSpacesRoute
  StaysTripsRoute: typeof StaysTripsRoute
  StaysIndexRoute: typeof StaysIndexRoute
  StaysBookRoomIdRoute: typeof StaysBookRoomIdRoute
  StaysBookingBookingIdRoute: typeof StaysBookingBookingIdRoute
  StaysCheckoutBookingIdRoute: typeof StaysCheckoutBookingIdRoute
  StaysEventEventIdRoute: typeof StaysEventEventIdRoute
  StaysPropertyPropertyIdRoute: typeof StaysPropertyPropertyIdRoute
  StaysSignBookingIdRoute: typeof StaysSignBookingIdRoute
}

const StaysRouteChildren: StaysRouteChildren = {
  StaysAccountRoute: StaysAccountRoute,
  StaysCommunityRoute: StaysCommunityRoute,
  StaysIncidentsRoute: StaysIncidentsRoute,
  StaysInvoicesRoute: StaysInvoicesRoute,
  StaysLoyaltyRoute: StaysLoyaltyRoute,
  StaysSpacesRoute: StaysSpacesRoute,
  StaysTripsRoute: StaysTripsRoute,
  StaysIndexRoute: StaysIndexRoute,
  StaysBookRoomIdRoute: StaysBookRoomIdRoute,
  StaysBookingBookingIdRoute: StaysBookingBookingIdRoute,
  StaysCheckoutBookingIdRoute: StaysCheckoutBookingIdRoute,
  StaysEventEventIdRoute: StaysEventEventIdRoute,
  StaysPropertyPropertyIdRoute: StaysPropertyPropertyIdRoute,
  StaysSignBookingIdRoute: StaysSignBookingIdRoute,
}

const StaysRouteWithChildren = StaysRoute._addFileChildren(StaysRouteChildren)

interface WebRouteChildren {
  WebCommunitiesRoute: typeof WebCommunitiesRoute
  WebEventsRoute: typeof WebEventsRoute
  WebIndexRoute: typeof WebIndexRoute
  WebBookRoomIdRoute: typeof WebBookRoomIdRoute
  WebBookingBookingIdRoute: typeof WebBookingBookingIdRoute
  WebCheckoutBookingIdRoute: typeof WebCheckoutBookingIdRoute
  WebCommunityCommunityIdRoute: typeof WebCommunityCommunityIdRoute
  WebEventEventIdRoute: typeof WebEventEventIdRoute
  WebRoomRoomIdRoute: typeof WebRoomRoomIdRoute
  WebSignBookingIdRoute: typeof WebSignBookingIdRoute
  WebUploadBookingIdRoute: typeof WebUploadBookingIdRoute
}

const WebRouteChildren: WebRouteChildren = {
  WebCommunitiesRoute: WebCommunitiesRoute,
  WebEventsRoute: WebEventsRoute,
  WebIndexRoute: WebIndexRoute,
  WebBookRoomIdRoute: WebBookRoomIdRoute,
  WebBookingBookingIdRoute: WebBookingBookingIdRoute,
  WebCheckoutBookingIdRoute: WebCheckoutBookingIdRoute,
  WebCommunityCommunityIdRoute: WebCommunityCommunityIdRoute,
  WebEventEventIdRoute: WebEventEventIdRoute,
  WebRoomRoomIdRoute: WebRoomRoomIdRoute,
  WebSignBookingIdRoute: WebSignBookingIdRoute,
  WebUploadBookingIdRoute: WebUploadBookingIdRoute,
}

const WebRouteWithChildren = WebRoute._addFileChildren(WebRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ReservarRoute: ReservarRoute,
  ReservarOkRoute: ReservarOkRoute,
  StaysRoute: StaysRouteWithChildren,
  WebRoute: WebRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
